/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './src/routes/__root'
import { Route as NotFoundRouteImport } from './src/routes/not-found'
import { Route as SessionRouteImport } from './src/routes/_session'
import { Route as ProtectedRouteImport } from './src/routes/_protected'
import { Route as IndexRouteImport } from './src/routes/index'
import { Route as SessionRegisterRouteImport } from './src/routes/_session/register'
import { Route as SessionLoginRouteImport } from './src/routes/_session/login'
import { Route as ProtectedFavoritesRouteImport } from './src/routes/_protected/favorites'
import { Route as ProtectedDashboardRouteImport } from './src/routes/_protected/dashboard'

const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRoute = SessionRouteImport.update({
  id: '/_session',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionRegisterRoute = SessionRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => SessionRoute,
} as any)
const SessionLoginRoute = SessionLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => SessionRoute,
} as any)
const ProtectedFavoritesRoute = ProtectedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/not-found': typeof NotFoundRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/favorites': typeof ProtectedFavoritesRoute
  '/login': typeof SessionLoginRoute
  '/register': typeof SessionRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/not-found': typeof NotFoundRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/favorites': typeof ProtectedFavoritesRoute
  '/login': typeof SessionLoginRoute
  '/register': typeof SessionRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/_session': typeof SessionRouteWithChildren
  '/not-found': typeof NotFoundRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/favorites': typeof ProtectedFavoritesRoute
  '/_session/login': typeof SessionLoginRoute
  '/_session/register': typeof SessionRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/not-found'
    | '/dashboard'
    | '/favorites'
    | '/login'
    | '/register'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/not-found' | '/dashboard' | '/favorites' | '/login' | '/register'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/_session'
    | '/not-found'
    | '/_protected/dashboard'
    | '/_protected/favorites'
    | '/_session/login'
    | '/_session/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  SessionRoute: typeof SessionRouteWithChildren
  NotFoundRoute: typeof NotFoundRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_session': {
      id: '/_session'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_session/register': {
      id: '/_session/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof SessionRegisterRouteImport
      parentRoute: typeof SessionRoute
    }
    '/_session/login': {
      id: '/_session/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof SessionLoginRouteImport
      parentRoute: typeof SessionRoute
    }
    '/_protected/favorites': {
      id: '/_protected/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof ProtectedFavoritesRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedFavoritesRoute: typeof ProtectedFavoritesRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedFavoritesRoute: ProtectedFavoritesRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

interface SessionRouteChildren {
  SessionLoginRoute: typeof SessionLoginRoute
  SessionRegisterRoute: typeof SessionRegisterRoute
}

const SessionRouteChildren: SessionRouteChildren = {
  SessionLoginRoute: SessionLoginRoute,
  SessionRegisterRoute: SessionRegisterRoute,
}

const SessionRouteWithChildren =
  SessionRoute._addFileChildren(SessionRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  SessionRoute: SessionRouteWithChildren,
  NotFoundRoute: NotFoundRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
